AWSTemplateFormatVersion: 2010-09-09
Description: Sample template that creates an EC2 and places it in the VPC created by the previous stack.

Parameters:            # This section declares parameters for the template
  
  NetworkStackName:              # Parameter logic name
    Description: >-              # YAML syntax for introducing multi-line strings
      Name of an active CloudFormation stack that contains the networking
      resources, such as the VPC and subnet that will be used in this stack.
    Type: String
    Default: lab-network         # Default value for the parameter

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair
    Default: ust-justinjia

Resources:

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fa3fe0fa7920f68e
      InstanceType: t2.micro
      KeyName: !Ref KeyName

      NetworkInterfaces:                          # Defines network interfaces for EC2 instance
        - GroupSet: [!Ref InstanceSecurityGroup]  # `GroupSet` is a list of security group IDs
          AssociatePublicIpAddress: true          # Assigns a public IP address to the network interface
          DeviceIndex: 0                          # Primary network interface (eth0)
          DeleteOnTermination: true               # Auto-deletes the network interface when the instance terminates
          SubnetId: 
            Fn::ImportValue: !Sub '${NetworkStackName}-SubnetID'  
            # The `Fn::ImportValue` function imports the value of the specified name exported by another stack
      
      UserData:
        Fn::Base64: |    # `|` is the YAML syntax for introducing multi-line strings; This text preserves line breaks exactly as written.
          #!/bin/bash
          dnf install -y httpd
          systemctl enable httpd
          systemctl start httpd
          echo '<html><img src="https://raw.githubusercontent.com/justinjiajia/cloud_security/refs/heads/main/labs/resources/AWS_logo_RGB.png" /><h1>Hello From Your Web Server!</h1></html>' > /var/www/html/index.html
      
        # The `Fn::Base64` function returns the Base64 representation of the input string. 
        # This function is typically used to pass encoded data to Amazon EC2 instances by way of the UserData property.

  DiskVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 1                          # Smallest possible - 1 GiB
      VolumeType: gp3                  # Recommended default type
      AvailabilityZone: !GetAtt Ec2Instance.AvailabilityZone
    DeletionPolicy: Snapshot

  DiskMountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref Ec2Instance
      VolumeId: !Ref DiskVolume
      Device: /dev/xvdh

  InstanceSecurityGroup:                   # Specifies a security group.
    Type: AWS::EC2::SecurityGroup                  
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: 
        Fn::ImportValue: !Sub '${NetworkStackName}-VPCID'
      SecurityGroupIngress:                # Inbound rules for the security group
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:

  EC2Instance:
    Description: Instance ID
    Value: !Ref Ec2Instance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceID'

  URL:
    Description: URL of the sample website
    Value: !Sub 'http://${Ec2Instance.PublicDnsName}'